/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  //output: 'export', // 添加这一行以生成静态输出
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    domains: [
      'localhost',
      'vercel.com',
      'images.unsplash.com',
      'source.unsplash.com',
      'picsum.photos',
      'placehold.co',
      'placekitten.com',
      'dummyimage.com',
      'via.placeholder.com',
      'randomuser.me',
      'avatars.githubusercontent.com',
      'ui-avatars.com',
      'cloudflare-ipfs.com',
      'loremflickr.com',
      'i.pravatar.cc',
      'robohash.org',
      'avatars.dicebear.com',
      'api.adorable.io',
      'placeimg.com',
      'placekitten.com',
      'placebear.com',
      'placecorgi.com',
      'placedog.net',
      'placesheen.com',
      'baconmockup.com',
      'placebeard.it',
      'fillmurray.com',
      'placecage.com',
      'stevensegallery.com',
      'placebacon.net',
      'placepuppy.it',
      'placeimg.com',
      'picsum.photos',
      'fastly.picsum.photos',
      'images.pexels.com',
      'pixabay.com',
      'cdn.pixabay.com',
      'media.giphy.com',
      'giphy.com',
      'tenor.com',
      'media.tenor.com',
      'media1.tenor.com',
      'media2.tenor.com',
      'media3.tenor.com',
      'media4.tenor.com',
      'media5.tenor.com',
      'media6.tenor.com',
      'media7.tenor.com',
      'media8.tenor.com',
      'media9.tenor.com',
    ],
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**',
      },
    ],
    unoptimized: true, // 静态导出时需要设置为true
  },
  experimental: {
    serverActions: {
      allowedOrigins: ['localhost:3000', '*'],
    },
  },
}

export default nextConfig
